name: agri_connect
description: "A new Flutter project."
publish_to: 'none' # Prevent publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1
  otp_autofill: ^4.1.0
  email_otp: ^3.0.2
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.2.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  android_path_provider: ^0.3.0
  lottie: ^3.1.3
  carousel_slider: ^5.0.0
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^14.6.1
  persistent_bottom_nav_bar: ^6.2.1
  image_picker: ^1.1.2
  provider: ^6.1.2
  file_picker: ^8.1.4
  http: ^1.2.2
  weather: ^3.1.1
  intl: ^0.20.1
  text: ^0.2.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  image_picker_web: ^4.0.0
  shared_preferences: ^2.3.4
  fluttertoast: ^8.2.8
  flutter_easyloading: ^3.0.0
  dropdown_button2: ^2.3.9
  firebase_storage: ^12.3.7
  line_awesome_flutter: ^3.0.1
  font_awesome_flutter: ^10.8.0
  encrypt: ^5.0.3
  image: ^4.3.0
  crypto: ^3.0.6
  flutter_secure_storage: ^4.2.1
  animate_do: ^3.3.4
  firebase_messaging: ^15.1.6
  flutter_app_badger: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
